### ISSUE TITLE
GCP: Remove requirement for TARGET-INSTANCE object in AliasIP only use case

### ISSUE THREAD

**Issue by f5-applebaum** [f5devcentral/f5-cloud-failover-extension#15]
Use case is that you would like to failover only AliasIps (vs Forwarding Rules).

Currently, the failover requires TARGET_INSTANCE objects to be created which is only needed for Forwarding Rules.  

Workaround is creating target instance objects:

https://cloud.google.com/sdk/gcloud/reference/compute/target-instances/create

gcloud compute target-instances create NAME --instance=INSTANCE [--description=DESCRIPTION] [--instance-zone=INSTANCE_ZONE] [--zone=ZONE] [GCLOUD_WIDE_FLAG …]

**Comment by f5-applebaum** [comment]
This is being tracked internally as:

AUTOSDK-195 - GCP: Remove requirement for TARGET-INSTANCE object in AliasIP only use case

**Comment by xags** [comment]
Could you give an example of this working? Creating the target-instances with the same name (for each F5) doesn't appear to do anything different. Would the declaration need anything removed/added to make this work? Is this also assuming that an internal LB is in-use? What if I am using default auto-created routes and not specifically defining them?

**Comment by alaari-f5** [comment]
Closing this issue

As of release CFE 1.2 we moved this CFE repo under F5Networks. Your issue was recreated there. To follow-up on this issue visit: 

https://github.com/F5Networks/f5-cloud-failover-extension/issues/11
