### ISSUE TITLE
[DOC] AWS: GIF uses incorrect terms for AWS objects

### ISSUE THREAD

**Issue by ajsq** [f5devcentral/f5-cloud-failover-extension#16]
The GIF for Failover Devent Diagram on the AWS page has the following errors:

- each BIG-IP is shown as existing in its own VPC - it should say AZ since all BIG-IPs must exist in a single VPC (Elastic IPs are scoped to VPC)
- the AZs in us-west-1 are named us-west-1a, us-west-1b, etc not us-west-1-a etc

**Comment by shyawnkarim** [comment]
Thanks for providing this feedback. I've created internal issue AUTOSDK-198 to fix the AWS Failover Event Diagram GIF labels.

**Comment by shyawnkarim** [comment]
This fix will be included in our next release =~ April 17, 2020.

**Comment by alaari-f5** [comment]
Closing this issue

As of release CFE 1.2 we moved this CFE repo under F5Networks. Your issue was recreated there. To follow-up on this issue visit: 

https://github.com/F5Networks/f5-cloud-failover-extension/issues/10
