### ISSUE TITLE
CFE uses hostname rather than device name when identifying traffic group

### ISSUE THREAD

**Issue by C0missar** [f5devcentral/f5-cloud-failover-extension#23]
If the host name of the device does not match the device name in the device group, CFE is unable to identify itself and determine which traffic groups are associated.  The result is that both devices think they are in standby, both report themselves as being in standby in response to a call to /mgmt/shared/cloud-failover/inspect, and no EIP re-association ever occurs.

The host name is written to the S3 f5cloudfailoverstate.json file, and the failover script searches for this name in the device group.

The CFE should only use the device name for identification of the traffic groups.

**Comment by shyawnkarim** [comment]
Thanks for reporting this bug. I've created internal ID AUTOSDK-262 to get this fixed.

**Comment by C0missar** [comment]
Any guess on when we'll see a fix?  I'm trying to determine how much effort to put in to a workaround.

There is one other CFT issue that would be very helpful to see addressed in the official released CFT, and that is issue #74.  I'm not sufficiently familiar with CFTs to know how to code these ready tests, and it seems to me that everyone would want the same things:


  *   Licensed
  *   Config loaded
  *   REST interface up
  *   Config UI running

There are other things that some people might want to check, but it seems to me that at a minimum, if any of these are not true, then we don't have a useful instance yet.

Thanks,

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com<mailto:michael.s.tetreault@sherwin.com>
http://www.sherwin-williams.com<http://www.sherwin-williams.com/>

**Comment by shyawnkarim** [comment]
I can give you an update once this bug has been prioritized for a sprint.

**Comment by alaari-f5** [comment]
Closing this issue

As of release CFE 1.2 we moved this CFE repo under F5Networks. Your issue was recreated there. To follow-up on this issue visit: 

https://github.com/F5Networks/f5-cloud-failover-extension/issues/4
