### ISSUE TITLE
RFE: CFE to support Azure Private Endpoints for Storage Account

### ISSUE THREAD

**Issue by tewfikm** [f5devcentral/f5-cloud-failover-extension#26]
Title : Request for Enhancement : CFE to support Azure Private Endpoints for Storage Account

Details:
For security reasons, customer is asking CFE to avoid performing API calls to Azure Public Endpoints.

Current CFE Azure provider is performing DNS resolution to Azure Storage account using connection String to Storage Account Public endpoint.

ASK:
CFE to Support Private Endpoint for storage accounts, by:

- giving option to configure storage account to switch to Private Endpoint on the VNET CFE is installed
- denying public access using storage FW

**Comment by shyawnkarim** [comment]
Thanks for submitting this enhancement. I've created internal issue ID AUTOSDK-273 and have added it to our backlog.

**Comment by alaari-f5** [comment]
Closing this issue

As of release CFE 1.2 we moved this CFE repo under F5Networks. Your issue was recreated there. To follow-up on this issue visit: https://github.com/F5Networks/f5-cloud-failover-extension/issues/2
