### ISSUE TITLE
IAM roles not clear

### ISSUE THREAD

**Issue by bradwithf5** [f5devcentral/f5-cloud-failover-extension#3]
I'm working with a customer and we're trying to understand the documentation on this. Where it says this:

    In GCP, go to IAM > Roles and create the member with the following scopes:

    compute-rw
    storage-rw
    cloud-platform

Are those roles supposed to be an equivalent to something Google uses here? If so, what roles are those supposed to be equal to? If not, and we're supposed to create them, what roles do we assign?

**Comment by shyawnkarim** [comment]
Thank you for reaching out to us with this issue. Our documentation is out of date and needs to be updated. I've gone ahead and created a Jira issue, #97, to fix this.

For now, try creating a Member with the role of Editor or Owner and then add it to the Service account of each instance. Let me know if that works for you.

**Comment by bradwithf5** [comment]
Will do thanks Shyawn

**Comment by jsevedge** [comment]
This has been resolved in https://github.com/f5devcentral/f5-cloud-failover-extension/releases/tag/v1.0.0
