### ISSUE TITLE
Does "scopingAddressRanges" refer to Alias IP ranges?

### ISSUE THREAD

**Issue by bradwithf5** [f5devcentral/f5-cloud-failover-extension#4]
In our docs for Google Cloud we reference "scopingAddressRanges" is this an equivalent to Alias IP ranges, if not what does it refer to in Google terminology?

**Comment by jsevedge** [comment]
@bradwithf5 "scopingAddressRanges" is related to the route failover feature and is used to match against the specific GCP route CIDR block when determining what routes should be updated.

**Comment by bradwithf5** [comment]
Thanks for that, what does it refer to in Google terminology? For context we're already referencing https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/quickstart.html#quickstart and so the data available on that page has already been taken into account. As Google does not use this term we're looking for what it compares to using the Google Cloud product

**Comment by jsevedge** [comment]
@bradwithf5 Understood, let me expand some.  It relates to the destination range on a GCP Compute Route... if deploying via terraform here is a concrete example below showing what that resource looks like.  So if you want ext-route to be updated on BIG-IP failover it needs to contain a matching scopingTag key/value as well as "192.0.2.0/24" should be in the scopingAddressRanges list.  Keep in mind, this configuration is only necessary if updating routes (i.e. forward proxy use case) is required.

```
resource "google_compute_route" "ext-route" {
  name        = "network-route-${module.utils.env_prefix}"
  description = " f5_cloud_failover_labels={\"f5_cloud_failover_label\":\"${module.utils.env_prefix}\",\"f5_self_ips\": [\"${google_compute_instance.vm01.network_interface.2.network_ip}\",\"${google_compute_instance.vm02.network_interface.2.network_ip}\"]}"
  dest_range  = "192.0.2.0/24"
  network     = "${google_compute_network.int_network.name}"
  next_hop_ip = "${google_compute_instance.vm02.network_interface.2.network_ip}"
  priority    = 100
}
```

**Comment by bradwithf5** [comment]
Thanks much appreciated!
