### ISSUE TITLE
delay time

### ISSUE THREAD

**Issue by yazankhader** [f5devcentral/f5-cloud-failover-extension#5]
will this eliminate the delay time we had using the normal ARM template for azure deployment active/standby.  <without Azure load balancer>
 

I didn’t find any information about the delay time in the below documents. 

https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/quickstart.html

https://github.com/f5devcentral/f5-cloud-failover-extension/releases 

finally, will we need two ip addresses per applications as we do with azure load balancer option? Or the same ip address will be moved between F5 VMs in case of failover? 

Thanks 
Yazan Khaer

**Comment by jsevedge** [comment]
@yazankhader Cloud failover extension does make use of Azure API calls to move IP configurations between NIC objects.  As such it is still subject to Azure API response times, unfortunately those API's can still be fairly slow (2-4 mins on average).

I have opened internal ID 104 to update the official documentation with a similar statement.

**Comment by jsevedge** [comment]
@yazankhader For the second question about addresses per application... you will only need a single address on both BIG-IP (virtual server) and the cloud resource (IP configuration) for the cluster.  The advantage of API failover is it treats failover more like traditional on-premise failover via GARP.  So it will determine if any virtual addresses in a floating traffic group exist and move that address to the corresponding NIC on the active BIG-IP.
