### ISSUE TITLE
example postman declaration for google error on environment

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/f5-cloud-failover-extension#6]
postman collection for Google show environment as gce. This errors and wants gcp instead.

"message": "Invalid declaration: [{\"keyword\":\"enum\",\"dataPath\":\".environment\",\"schemaPath\":\"#/properties/environment/enum\",\"params\":{\"allowedValues\":[\"aws\",\"azure\",\"gcp\"]},\"message\":\"should be equal to one of the allowed values\"}]"

I changed environment to 'gcp' instead of 'gce' and it worked. This matches documentation of gcp example declaration.

my workaround...snippet...
{
    "class": "Cloud_Failover",
    "environment": "gcp",
    "externalStorage": {
        "scopingTags": {

**Comment by jsevedge** [comment]
@JeffGiroux This will be resolved in the next release.  Internal ID AUTOSDK-132

**Comment by jsevedge** [comment]
This has been resolved in https://github.com/f5devcentral/f5-cloud-failover-extension/releases/tag/v1.0.0
