### ISSUE TITLE
Routes do not move and give status code 400 in Google

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/f5-cloud-failover-extension#7]
GCP - unable to update route table to point to next hop...snippet error below. All tagging and permissions seem to be correct. Using dev RPM and dev docs with correct dev example declarations.

Side note:
If there are no routes to move, then I get a 200 result after the failover. JSON file in storage bucket says the same. If I add a route in Google that matches my declaration, then see failures. Routes do not move, but everything else is moving successfully.

##Troubleshooting
/var/log/restnoded/restnoded.log
Fri, 17 Jan 2020 19:44:10 GMT - info: [f5-cloud-failover] Performing failover - execute
Fri, 17 Jan 2020 19:44:10 GMT - info: [f5-cloud-failover] Performing Failover - discovery
Fri, 17 Jan 2020 19:44:11 GMT - info: [f5-cloud-failover] Performing Failover - update
Fri, 17 Jan 2020 19:44:12 GMT - info: [f5-cloud-failover] Disassociate NICs successful.
Fri, 17 Jan 2020 19:44:12 GMT - info: [f5-cloud-failover] Updated forwarding rules successfully
Fri, 17 Jan 2020 19:44:12 GMT - info: [f5-cloud-failover] Associate NICs successful.
Fri, 17 Jan 2020 19:44:18 GMT - severe: [f5-cloud-failover] failover.execute() error: https://www.googleapis.com/compute/v1/projects/xxxxxxxx/global/routes/ status code 400, status message Bad Request Error: https://www.googleapis.com/compute/v1/projects/xxxxxxxx/global/routes/ status code 400, status message Bad Request
    at ClientRequest.executor.request (/var/config/rest/iapps/f5-cloud-failover/node_modules/@f5devcentral/f5-cloud-libs/lib/httpUtil.js:164:41)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:607:20)

Example declaration:
{
    "message": "success",
    "declaration": {
        "class": "Cloud_Failover",
        "environment": "gcp",
        "externalStorage": {
            "scopingTags": {
                "goog-dm": "jg-f5-api-ha2"
            }
        },
        "failoverAddresses": {
            "scopingTags": {
                "goog-dm": "jg-f5-api-ha2"
            }
        },
        "failoverRoutes": {
            "scopingTags": {
                "goog-dm": "jg-f5-api-ha2"
            },
            "scopingAddressRanges": [
                {
                    "range": "10.1.20.0/24"
                }
            ],
            "defaultNextHopAddresses": {
                "discoveryType": "static",
                "items": [
                    "10.1.10.5",
                    "10.1.10.6"
                ]
            }
        },
        "controls": {
            "class": "Controls",
            "logLevel": "info"
        },
        "schemaVersion": "0.9.0"
    }
}

Storage bucket f5cloudfailoverstate.json:
{"taskState":"FAILED","message":"Failover failed because of failover.execute() error: https://www.googleapis.com/compute/v1/projects/xxxxxxxx/global/routes/ status code 400, status message Bad Request Error: https://www.googleapis.com/compute/v1/projects/xxxxxxxx/global/routes/ status code 400, status message Bad Request\n    at ClientRequest.executor.request (/var/config/rest/iapps/f5-cloud-failover/node_modules/@f5devcentral/f5-cloud-libs/lib/httpUtil.js:164:41)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)\n    at TLSSocket.socketOnData (_http_client.js:440:20)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at TLSSocket.Readable.push (_stream_readable.js:208:10)\n    at TLSWrap.onread (net.js:607:20)","timestamp":"2020-01-17T19:44:18.127Z","instance":"bigip2-jg-f5-api-ha2.c.f5-4136-mspteam-dev.internal","failoverOperations":{"addresses":{"nics":{"disassociate":[],"associate":[]},"fwdRules":{"operations":[]}},"routes":{"operations":[{"name":"jg-route1","description":"f5_cloud_failover_labels={\"goog-dm\":\"jg-f5-api-ha2\"}","network":"https://www.googleapis.com/compute/v1/projects/xxxxxxxx/global/networks/jgiroux-net-ext","destRange":"10.1.20.0/24","priority":1000,"nextHopInstance":"https://www.googleapis.com/compute/v1/projects/xxxxxxxx/zones/us-west1-b/instances/bigip1-jg-f5-api-ha2","nextHopIp":"10.1.10.6"}]}}}

**Comment by JeffGiroux** [comment]
I got it working thanks to @jsevedge 

You have to make sure the route you create in google is targeting a next hop address instead of next hop instance. The scripts are looking for address. Once i fixed this, I now have 200 OK successful failover of all items: routes, aliasIP, forwarding rules.
 
BAD - My original route was created like this...
gcloud compute routes create jg-route1 --destination-range=10.1.20.0/24 --network=jgiroux-net-ext --next-hop-instance=bigip2-jg-f5-api-ha2 --description='f5_cloud_failover_labels={"goog-dm":"jg-f5-api-ha2"}'

GOOD - Example route creation and "labels" used in description field:
gcloud compute routes create jg-route1 --destination-range=10.1.20.0/24 --network=jgiroux-net-ext --next-hop-address=10.1.10.6 --description='f5_cloud_failover_labels={"goog-dm":"jg-f5-api-ha2"}'
 
Self IP has to match one of your self IPs that are noted in the declaration you POST as well as the address range...snippet...
https://clouddocs.f5networks.net/products/extensions/f5-cloud-failover/latest/userguide/gcp.html#example-declaration

        "failoverRoutes": {
            "scopingTags": {
                "goog-dm": "jg-f5-api-ha2"
            },
            "scopingAddressRanges": [
                {
                    "range": "10.1.20.0/24"
                }
            ],
            "defaultNextHopAddresses": {
                "discoveryType": "static",
                "items": [
                    "10.1.10.5",
                    "10.1.10.6"
                ]
            }


Documentation update and clarity around this would be very helpful along with screenshots.

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with this issue. I've gone ahead and created Jira issue #138 to give more detailed documentation arounds routes and next hop address.
