### ISSUE TITLE
Documentation update: Google failover topolopy pic-gif is inaccurate

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/f5-cloud-failover-extension#8]
Diagram animates and shows public IPs are linked with aliasIPs and this is not accurate. The forwarding rule will take a public IP and send to NIC0 of the VM. It does not perform any NAT and therefore the F5 virtual server should also be a public IP.

Reference the animated topology GIF here. This diagram needs correction.
https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/gcp.html

The correct flow for public IP flows (does not apply to ILB use case)
1. forwarding rule for public IP 52.11.22.33 to target instance F5 on NIC0
2. NIC0 should be depicted in GIF diagram
3. F5 virtual server IP should be represented by same pubIP 52.11.22.33 on the F5 as "VIP" or similar name..."Listener IP"

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with this issue. I've gone ahead and created Jira issue #137 to get this diagram updated.
