### ISSUE TITLE
Error 401 unauthorized in Google - received after an hour of non-failover activity

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/f5-cloud-failover-extension#9]
I have a successfully working HA pair and CFE deployment. I used the 3nic supported HA via API template. If my BIG-IP cluster does not have any failover activity for a while, then upon next failover event the CFE throws a 401 unauthorized error. Permission are correct. Already validated successfully initial CFE setup by failing over and getting valid 200 OK and good responses from /trigger.

##Template
https://github.com/F5Networks/f5-google-gdm-templates/tree/master/supported/standalone/3nic/existing-stack/payg

##Repro
1. Deploy template HA via API 3nic supported
2. Install CFE and setup then test a few failovers. Validate you get 200 OK and cloud objects move.
3. Walk away for a few hours and do NOT let boxes failover...keep in current state
4. After a few hours, perform failover
5. Check endpoint /trigger and receive 401. Logs will show similar

### /trigger response

{
    "taskState": "FAILED",
    "message": "Failover failed because of failover.execute() error: https://www.googleapis.com/compute/v1/projects/xxxxx/global/routes status code 401, status message Unauthorized Error: https://www.googleapis.com/compute/v1/projects/xxxxx/global/routes status code 401, status message Unauthorized\n    at ClientRequest.executor.request (/var/config/rest/iapps/f5-cloud-failover/node_modules/@f5devcentral/f5-cloud-libs/lib/httpUtil.js:164:41)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)\n    at TLSSocket.socketOnData (_http_client.js:440:20)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at TLSSocket.Readable.push (_stream_readable.js:208:10)\n    at TLSWrap.onread (net.js:607:20)",
    "timestamp": "2020-01-18T00:59:37.197Z",
    "instance": "bigip1-jg-f5-api-ha2.c.xxxxx.internal",
    "failoverOperations": {
        "addresses": {
            "nics": {
                "disassociate": [],
                "associate": []
            },
            "fwdRules": {
                "operations": []
            }
        },
        "routes": {
            "operations": [
                {
                    "name": "jg-route1",
                    "description": "f5_cloud_failover_labels={\"goog-dm\":\"jg-f5-api-ha2\"}",
                    "network": "https://www.googleapis.com/compute/v1/projects/xxxxx/global/networks/jgiroux-net-ext",
                    "destRange": "10.1.20.0/24",
                    "priority": 1000,
                    "nextHopIp": "10.1.10.5"
                }
            ]
        }
    },
    "code": 400
}

### cat /var/log/restnoded/restnoded.log

Sat, 18 Jan 2020 00:59:36 GMT - finest: socket 633 opened
Sat, 18 Jan 2020 00:59:36 GMT - info: [f5-cloud-failover] Performing failover - execute
Sat, 18 Jan 2020 00:59:37 GMT - info: [f5-cloud-failover] Performing Failover - discovery
Sat, 18 Jan 2020 00:59:37 GMT - severe: [f5-cloud-failover] failover.execute() error: https://www.googleapis.com/compute/v1/projects/xxxxx/global/routes status code 401, status message Unauthorized Error: https://www.googleapis.com/compute/v1/projects/xxxxx/global/routes status code 401, status message Unauthorized
    at ClientRequest.executor.request (/var/config/rest/iapps/f5-cloud-failover/node_modules/@f5devcentral/f5-cloud-libs/lib/httpUtil.js:164:41)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:607:20)
Sat, 18 Jan 2020 00:59:42 GMT - finest: socket 633 closed

**Comment by jsevedge** [comment]
Internal ID AUTOSDK-133 created to track this.

**Comment by jsevedge** [comment]
This has been resolved in https://github.com/f5devcentral/f5-cloud-failover-extension/releases/tag/v1.0.0
